[build]
target = "x86_64-heavenos.json"

[target.x86_64-heavenos]
rustflags = [
    "-C", "link-arg=-Tkernel/linker.ld",
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
]

[unstable]
json-target-spec = true
