[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -drive format=raw,file="
rustflags = ["-C", "link-arg=-Tkernel/linker.ld", "-C", "code-model=kernel"]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
